// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace PRM392_BookSoccerYard.API.Models;

public partial class OrderDetail
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public int? OrderId { get; set; }

    public int? QuantityService { get; set; }

    public double? FinalPrice { get; set; }

    public double? TotalPrice { get; set; }

    public int? ServiceId { get; set; }

    public virtual Order Order { get; set; }

    public virtual Service Service { get; set; }
}