// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace PRM392_BookSoccerYard.API.Models;

public partial class Slot
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public TimeSpan StartTime { get; set; }

    public TimeSpan EndTime { get; set; }

    public bool Status { get; set; }

    public string Name { get; set; }

    public double PriceUp { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}